### ISSUE TITLE
Erro ao validar contracts aninhados

### ISSUE THREAD

**Issue by LucasLopesr** [carlosbritojun/jflunt#1]
Fiz a seguinte regra 

`
addNotifications(
                new Contract().requires().isNotNull(foo.getBar(), "","")
                        .isGreaterThan(foo.getBar(), 0, ""));
`

Onde getBar() retorna nulo, isso gera null pointer na classe de comparação:
IntegerValidationContract.java 
`
if (Integer.compare(val, comparer) <= 0)
`

**Comment by carlosbritojun** [comment]
Recursos de programação defensiva contornam esse cenário. Caso queria isso dentro da lib, abra uma PR que terei o enorme prazer de aceitá-la Perdoe-me a demora na resposta.

**Comment by carlosbritojun** [comment]
finished
